name: EDK2 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.5
    - name: CI Build
      run: chmod +x ci-build.sh && ./ci-build.sh

    - uses: actions/upload-artifact@v4.3.3
      with:
        name: OrangePi Zero3 UEFI
        path: ./workspace/UEFI
